### ISSUE TITLE
Failes to build on gcc 4.9.x

### ISSUE THREAD

**Issue by GoogleCodeExporter** [steem-engine/steem-engine#6]
```
What steps will reproduce the problem?
1. Attempt to compile with GCC 4.9.x


What is the expected output? What do you see instead?

It builds. Multiple errors and warnings resulting in a failed build.


What version of the product are you using? On what operating system?

trunk / debian 7 


Please provide any additional information below.

stephen@development:~/compileZone/steem-engine-read-only/X-build$ make
mkdir -p ./obj
nasm -felf -o./obj/asm_draw.o -i../steem/asm/ ../steem/asm/asm_draw.asm
nasm -felf -o./obj/asm_osd.o -i../steem/asm/ ../steem/asm/asm_osd_draw.asm
mkdir -p obj output
make res
make[1]: Entering directory 
'/home/stephen/compileZone/steem-engine-read-only/X-build'
nasm -felf -o./obj/resource.o -i../steem/ ../steem/rc/resource.asm
make[1]: Leaving directory 
'/home/stephen/compileZone/steem-engine-read-only/X-build'
make helper
make[1]: Entering directory 
'/home/stephen/compileZone/steem-engine-read-only/X-build'
g++ -o ./obj/helper.o -c ../steem/helper.cpp -I../include -I../steem/code 
-I../3rdparty/unrarlib -I../3rdparty/zlib/contrib/minizip -I../3rdparty/zlib 
-I../3rdparty/portaudio/src/common -I../3rdparty/portaudio/include 
-I../3rdparty/rtaudio -w -Wall -DUNIX -DLINUX
In file included from ../include/x/hxc.cpp:594:0,
                 from ../steem/helper.cpp:36:
../include/x/hxc_listview.cpp: In member function ‘void 
hxc_listview::drag_end(int, int)’:
../include/x/hxc_listview.cpp:1017:33: error: cast from 
‘hxc_listview_drop_struct*’ to ‘int’ loses precision [-fpermissive]
  notifyproc(this,LVN_DROP,(int)&ds);
                                 ^
In file included from ../steem/helper.cpp:41:0:
../include/x/hxc_dir_lv.cpp: In member function ‘bool 
hxc_dir_lv::refresh_fol()’:
../include/x/hxc_dir_lv.cpp:112:75: error: cast from ‘char*’ to ‘int’ 
loses precision [-fpermissive]
                 int newn=notifyproc(this,DLVN_GETTYPE,int(notify_path.Text));
                                                                           ^
../include/x/hxc_dir_lv.cpp: In member function ‘EasyStr 
hxc_dir_lv::movecopylink_item(int, EasyStr, EasyStr)’:
../include/x/hxc_dir_lv.cpp:190:51: error: cast from ‘dlv_ccn_struct*’ to 
‘int’ loses precision [-fpermissive]
       notifyproc(this,DLVN_CONTENTSCHANGE,int(&ccn));
                                                   ^
../include/x/hxc_dir_lv.cpp:197:51: error: cast from ‘dlv_ccn_struct*’ to 
‘int’ loses precision [-fpermissive]
       notifyproc(this,DLVN_CONTENTSCHANGE,int(&ccn));
                                                   ^
../include/x/hxc_dir_lv.cpp: In static member function ‘static int 
hxc_dir_lv::lv_notifyproc(hxc_listview*, int, int)’:
../include/x/hxc_dir_lv.cpp:220:91: error: cast from ‘char*’ to ‘int’ 
loses precision [-fpermissive]
         if (This->notifyproc) ret=This->notifyproc(This,DLVN_FOLDERCHANGE,int(new_fol.Text));
                                                                                           ^
../include/x/hxc_dir_lv.cpp:312:65: error: cast from 
‘hxc_listview_drop_struct*’ to ‘int’ loses precision [-fpermissive]
      if (This->notifyproc) This->notifyproc(This,DLVN_DROP,(int)ds);
                                                                 ^
../include/x/hxc_dir_lv.cpp: In member function ‘void 
hxc_dir_lv::delete_item()’:
../include/x/hxc_dir_lv.cpp:393:49: error: cast from ‘dlv_ccn_struct*’ to 
‘int’ loses precision [-fpermissive]
     notifyproc(this,DLVN_CONTENTSCHANGE,int(&ccn));
                                                 ^
../include/x/hxc_dir_lv.cpp:407:49: error: cast from ‘dlv_ccn_struct*’ to 
‘int’ loses precision [-fpermissive]
     notifyproc(this,DLVN_CONTENTSCHANGE,int(&ccn));
                                                 ^
../include/x/hxc_dir_lv.cpp:417:65: error: cast from ‘char*’ to ‘int’ 
loses precision [-fpermissive]
   if (notifyproc) notifyproc(this,DLVN_ITEMDELETED,int(file.Text));
                                                                 ^
../include/x/hxc_dir_lv.cpp: In member function ‘void 
hxc_dir_lv::rename_item()’:
../include/x/hxc_dir_lv.cpp:447:51: error: cast from ‘dlv_ccn_struct*’ to 
‘int’ loses precision [-fpermissive]
       notifyproc(this,DLVN_CONTENTSCHANGE,int(&ccn));
                                                   ^
../include/x/hxc_dir_lv.cpp:456:51: error: cast from ‘dlv_ccn_struct*’ to 
‘int’ loses precision [-fpermissive]
       notifyproc(this,DLVN_CONTENTSCHANGE,int(&ccn));
                                                   ^
../include/x/hxc_dir_lv.cpp:464:55: error: cast from ‘char*’ to ‘int’ 
loses precision [-fpermissive]
         notifyproc(this,DLVN_FOLDERMOVED,int(file.Text));
                                                       ^
Makefile:89: recipe for target 'helper' failed
make[1]: *** [helper] Error 1
make[1]: Leaving directory 
'/home/stephen/compileZone/steem-engine-read-only/X-build'
Makefile:59: recipe for target 'all' failed
make: *** [all] Error 2

stephen@development:~/compileZone/steem-engine-read-only/X-build$ g++ --version
g++ (Debian 4.9.1-4) 4.9.1
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


stephen@development:~/compileZone/steem-engine-read-only/X-build$ uname -a
Linux development 3.2.0-4-amd64 #1 SMP Debian 3.2.51-1 x86_64 GNU/Linux





```

Original issue reported on code.google.com by `sle...@vavi.co.uk` on 25 Aug 2014 at 9:09

**Comment by miniupnp** [comment]
steem should be compiled in 32bit / i386.
Add -m32 to CFLAGS
